### ISSUE TITLE
New feature request:

### ISSUE THREAD

**Issue by wmegel** [theburningmonk/serverless-logging-config#1]
# This is a Feature Proposal

## Description

Hi,

Could it be possible to add these features (as discussed in Twitter):
- Possibility for some functions to log to the shared group and some to its own default log group
- Possibility for all lambdas to use their default group, but enable json logs for all lambdas.

Best regards.

**Comment by mike-perry-flashparking** [comment]
I too would like to keep my existing log group names but just enable JSON logs for them.
